[project]
name = "datamaker-py"
version = "0.7.0"
description = "The official Python library for the Automators DataMaker API."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "ruff>=0.14.0",
    "tool>=0.8.0",
]
