"""Spec schema names, resolved to the classes the generator produced.

Generated by scripts/generate_schema.py - do not edit by hand.

Import types from HERE, not from `generated.schema`: the generator lets an
inline schema take a bare name like `Plan` and renames the real component to
`Plan1`, so the numbering is not stable across spec changes. This module is
re-derived by matching key sets against the spec on every generation.
"""

from .generated import schema as _s

# PackInstallListItem: allOf composition (PackInstall + installedByName)
# SchemaGraphNavigation: only referenced inside a union; no standalone class
# SetDetail: allOf composition (Set + createdByName) is merged away

AddressAvailability = _s.AddressAvailability
ApiError = _s.ApiError
ApiKey = _s.ApiKey
ApiKeyValidation = _s.ApiKeyValidation
ApiMessageError = _s.ApiMessageError
ApprovalDecision = _s.ApprovalDecision
ApprovalStatus = _s.ApprovalStatus
AuditEvent = _s.AuditEvent
AuditEventRef = _s.AuditEventRef
BuiltinSkill = _s.BuiltinSkill
CapabilityCatalogItem = _s.CapabilityCatalogItem
Chat = _s.Chat
ChatAsset = _s.ChatAsset
ClassifiedFields = _s.ClassifiedFields
ConnectionTable = _s.ConnectionTable
ConnectionVerdict = _s.ConnectionVerdict
CsrfToken = _s.CsrfToken
CsvBatchUploadError = _s.CsvBatchUploadError
CsvBatchUploadResult = _s.CsvBatchUploadResult
CurrentUser = _s.CurrentUser
CustomDataType = _s.CustomDataType
DatabaseExportResult = _s.DatabaseExportResult
DatabaseTemplatesProposal = _s.DatabaseTemplatesProposal
DatamakerConfig = _s.DatamakerConfig
DeletedResult = _s.DeletedResult
EffectivePermissions = _s.EffectivePermissions
Endpoint = _s.Endpoint
EndpointFolder = _s.EndpointFolder
Feedback = _s.Feedback
FieldType = _s.FieldType
GeneratedData = _s.GeneratedData
GeneratedTemplateField = _s.GeneratedTemplateField
GeneratedTemplateFields = _s.GeneratedTemplateFields
ImageAnalysisResult = _s.ImageAnalysisResult
Integration = _s.Integration
KeyMapDeleteResult = _s.KeyMapDeleteResult
KeyMapEntriesPage = _s.KeyMapEntriesPage
KeyMapEntry = _s.KeyMapEntry
KeyMapLookupResult = _s.KeyMapLookupResult
KeyMapSummary = _s.KeyMapSummary
KeyMapUpsertResult = _s.KeyMapUpsertResult
License = _s.License
LicenseStatus = _s.LicenseStatus
LogCleanupResult = _s.LogCleanupResult
LogoutResult = _s.LogoutResult
MaskingPolicy = _s.MaskingPolicy
MemberInviteResult = _s.MemberInviteResult
MemberRoleAssignment = _s.MemberRoleAssignment
PackCatalog = _s.PackCatalog
PackCreatedCounts = _s.PackCreatedCounts
PackExportResult = _s.PackExportResult
PackImportDiff = _s.PackImportDiff
PackInstall = _s.PackInstall
PackInstallResult = _s.PackInstallResult
PdfAnalysisResult = _s.PdfAnalysisResult
PermissionCatalogue = _s.PermissionCatalogue
Plan = _s.Plan1
PlanDeleteResult = _s.PlanDeleteResult
PlanRun = _s.PlanRun
PlanRunAccepted = _s.PlanRunAccepted
PlanRunAck = _s.PlanRunAck
PlanRunFile = _s.PlanRunFile
PlanRunFileAck = _s.PlanRunFileAck
PlanSignoff = _s.PlanSignoff
PreferencesUpdateError = _s.PreferencesUpdateError
PreferencesUpdateResult = _s.PreferencesUpdateResult
PreviewResult = _s.PreviewResult
Project = _s.Project
PythonExecutionError = _s.PythonExecutionError
PythonExecutionResult = _s.PythonExecutionResult
Role = _s.Role
SapServiceCatalog = _s.SapServiceCatalog
Scenario = _s.Scenario1
ScenarioDiagramRegenerateAccepted = _s.ScenarioDiagramRegenerateAccepted
ScenarioEnvironmentVariableList = _s.ScenarioEnvironmentVariableList
ScenarioEnvironmentVariables = _s.ScenarioEnvironmentVariables
ScenarioFile = _s.ScenarioFile
ScenarioFileCreated = _s.ScenarioFileCreated
ScenarioJob = _s.ScenarioJob
ScenarioJobStatus = _s.ScenarioJobStatus
ScenarioJobs = _s.ScenarioJobs
ScenarioLog = _s.ScenarioLog
SchemaGraphChange = _s.SchemaGraphChange
SchemaGraphConnectResult = _s.SchemaGraphConnectResult
SchemaGraphDiffResult = _s.SchemaGraphDiffResult
SchemaGraphEntity = _s.SchemaGraphEntity
SchemaGraphEntityContext = _s.SchemaGraphEntityContext
SchemaGraphMinedField = _s.SchemaGraphMinedField
SchemaGraphPathResult = _s.SchemaGraphPathResult
SchemaGraphPreviewResult = _s.SchemaGraphPreviewResult
SchemaGraphProperty = _s.SchemaGraphProperty
SchemaGraphRefreshResult = _s.SchemaGraphRefreshResult
SchemaGraphSampleResult = _s.SchemaGraphSampleResult
SchemaGraphSearchResult = _s.SchemaGraphSearchResult
SchemaGraphTemplateResult = _s.SchemaGraphTemplateResult
SessionTokens = _s.SessionTokens
Set = _s.Set
Shortcut = _s.Shortcut
Skill = _s.Skill
StringList = _s.StringList
SuccessResult = _s.SuccessResult
Team = _s.Team
TeamMember = _s.TeamMember
TeamSetupResult = _s.TeamSetupResult
TeamSkill = _s.TeamSkill
Template = _s.Template2
TemplateFolder = _s.TemplateFolder
ToscaOnPremWorkspaces = _s.ToscaOnPremWorkspaces
ToscaWorkspaces = _s.ToscaWorkspaces
UploadResult = _s.UploadResult
UploadTextResult = _s.UploadTextResult
User = _s.User
UserPreferences = _s.UserPreferences
WorkerWorkspaceInfo = _s.WorkerWorkspaceInfo
WorkerWorkspaceListing = _s.WorkerWorkspaceListing
WorkerWorkspaceSyncResult = _s.WorkerWorkspaceSyncResult
WorkerWorkspaceUploadResult = _s.WorkerWorkspaceUploadResult
WorkspaceListing = _s.WorkspaceListing
WorkspaceStorage = _s.WorkspaceStorage
WorkspaceUploadResult = _s.WorkspaceUploadResult
